# Tên của Workflow, sẽ hiển thị trên tab "Actions" của GitHub
name: Compile LaTeX to PDF & HTML, then Deploy to GitHub Pages

# Cấu hình khi nào Workflow này sẽ chạy
on:
  push:
    branches: [ main ] # Kích hoạt khi có commit được push lên branch 'main'
                       # Đảm bảo 'main' là tên branch chính của bạn (có thể là 'master')
  workflow_dispatch: # Cho phép bạn chạy Workflow này thủ công từ GitHub UI

# Cấu hình quyền hạn cần thiết cho Workflow
permissions:
  contents: read      # Cần để checkout mã nguồn của repository
  pages: write        # Cần để upload và triển khai nội dung lên GitHub Pages
  id-token: write     # Cần cho OpenID Connect (OIDC) để xác thực an toàn với GitHub Pages

# Định nghĩa các công việc (Jobs) trong Workflow
jobs:
  # Job đầu tiên: Biên dịch tài liệu và tạo các artifacts
  build-documents:
    runs-on: ubuntu-latest # Chạy job này trên một máy ảo Ubuntu mới nhất

    steps:
      - name: Checkout repository # Bước: Kéo mã nguồn của repository về máy ảo runner
        uses: actions/checkout@v4 # Sử dụng action 'checkout' phiên bản 4

      - name: Create output directories # Bước: Tạo các thư mục đầu ra
        run: |
          mkdir -p output/pdf # Thư mục để chứa file PDF đã biên dịch
          mkdir -p output/html # Thư mục để chứa các file HTML đã chuyển đổi (cho GitHub Pages)
          # 'mkdir -p' sẽ tạo thư mục nếu nó chưa tồn tại, hoặc không làm gì nếu đã tồn tại

      # Bước 1: Biên dịch LaTeX sang PDF bằng pdflatex
      - name: Compile LaTeX to PDF with pdflatex
        uses: xu-cheng/latex-action@v2 # Sử dụng action 'latex-action' phiên bản 2
        with:
          root_file: main.tex # Tên file LaTeX gốc của bạn (phải nằm ở thư mục gốc của repo)
          compiler: pdflatex # Chỉ định trình biên dịch LaTeX là pdflatex
          # Quan trọng: Đã sửa từ 'latexmk_options' sang 'args' để khắc phục cảnh báo
          args: '-outdir=output/pdf' # Truyền tùy chọn cho latexmk/compiler để xuất PDF vào thư mục output/pdf

      # Bước 2: Chuyển đổi LaTeX sang HTML bằng make4ht
      # make4ht là một phần của tex4ht, được thiết kế chuyên biệt để chuyển đổi LaTeX sang HTML
      - name: Convert LaTeX to HTML with make4ht
        run: |
          # Chạy make4ht. Lệnh này sẽ tạo ra main.html, main.css và các file liên quan
          # trong thư mục output/html.
          # Sử dụng `-d` để chỉ định thư mục đầu ra.
          make4ht -d output/html main.tex "html"

          # Đổi tên main.html thành index.html để nó là trang mặc định khi truy cập GitHub Pages URL
          mv output/html/main.html output/html/index.html

          # Kiểm tra xem make4ht đã tạo ra file index.html chưa (sau khi đổi tên)
          ls -l output/html/ # Liệt kê nội dung thư mục output/html để debug
          if [ ! -f output/html/index.html ]; then
            echo "Lỗi: index.html không được tạo ra hoặc đổi tên thành công bởi make4ht."
            exit 1 # Thoát job nếu file không tồn tại
          fi

      # Bước 3: Upload file PDF đã biên dịch làm Artifact
      # Artifacts là các file được tạo ra trong quá trình chạy workflow mà bạn muốn lưu trữ hoặc tải về.
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4 # Sử dụng action 'upload-artifact' phiên bản 4
        with:
          name: compiled-pdf # Tên của artifact (sẽ hiển thị trên GitHub Actions)
          path: output/pdf/main.pdf # Đường dẫn đến file PDF đã biên dịch

      # Bước 4: Upload các file HTML làm Artifact cho GitHub Pages
      # Các file trong thư mục output/html sẽ được nén và chuẩn bị cho quá trình triển khai GitHub Pages.
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3 # Sử dụng action 'upload-pages-artifact' phiên bản 3
        with:
          path: output/html # Đường dẫn đến thư mục chứa tất cả các file HTML và tài nguyên liên quan

  # Job thứ hai: Triển khai các file đã tạo lên GitHub Pages
  deploy-pages:
    environment:
      name: github-pages # Chỉ định môi trường triển khai là 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }} # Lấy URL của trang đã triển khai
    runs-on: ubuntu-latest # Chạy job này trên môi trường Ubuntu mới nhất
    needs: build-documents # Job này sẽ chỉ chạy sau khi job 'build-documents' hoàn thành thành công

    steps:
      - name: Deploy to GitHub Pages # Bước: Triển khai nội dung lên GitHub Pages
        id: deployment # Đặt ID cho bước này để có thể tham chiếu URL sau
        uses: actions/deploy-pages@v4 # Sử dụng action 'deploy-pages' phiên bản 4