name: Compile LaTeX to PDF & HTML, then Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-documents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directories
        run: |
          mkdir -p output/pdf
          mkdir -p output/html

      - name: Compile LaTeX to PDF with pdflatex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: pdflatex
          args: '-outdir=output/pdf'

      - name: Convert LaTeX to HTML with make4ht
        run: |
          make4ht -d output/html main.tex "html"
          mv output/html/main.html output/html/index.html
          ls -l output/html/
          if [ ! -f output/html/index.html ]; then
            echo "Lỗi: index.html không được tạo ra."
            exit 1
          fi

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: output/pdf/main.pdf

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/html

  # ⚠️ Bổ sung bước thiết lập GitHub Pages trước khi deploy
  setup-pages:
    runs-on: ubuntu-latest
    needs: build-documents
    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-documents, setup-pages]  # cần cả setup và build xong

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
