# Tên của Workflow, sẽ hiển thị trên tab "Actions" của GitHub
name: Compile LaTeX to PDF & HTML, then Deploy to GitHub Pages

# Cấu hình khi nào Workflow này sẽ chạy
on:
  push:
    branches: [ main ] # Kích hoạt khi có commit được push lên branch 'main'
  workflow_dispatch: # Cho phép bạn chạy Workflow này thủ công từ GitHub UI

# Cấu hình quyền hạn cần thiết cho Workflow
permissions:
  contents: read      # Cần để checkout mã nguồn của repository
  pages: write        # Cần để upload và triển khai nội dung lên GitHub Pages
  id-token: write     # Cần cho OpenID Connect (OIDC) để xác thực an toàn với GitHub Pages

# Định nghĩa các công việc (Jobs) trong Workflow
jobs:
  # Job đầu tiên: Biên dịch tài liệu và tạo các artifacts
  build-documents:
    runs-on: ubuntu-latest # Chạy job này trên một máy ảo Ubuntu mới nhất

    steps:
      - name: Checkout repository # Bước: Kéo mã nguồn của repository về máy ảo runner
        uses: actions/checkout@v4 # Sử dụng action 'checkout' phiên bản 4

      - name: Create output directories # Bước: Tạo các thư mục đầu ra
        run: |
          mkdir -p output/pdf # Thư mục để chứa file PDF đã biên dịch
          mkdir -p output/html # Thư mục để chứa các file HTML đã chuyển đổi (cho GitHub Pages)

      # BƯỚC MỚI & QUAN TRỌNG: Cài đặt TeX Live đầy đủ (bao gồm tex4ht và make4ht)
      # Đây là cách đáng tin cậy nhất để đảm bảo make4ht có sẵn.
      - name: Install full TeX Live (including make4ht)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full # Cài đặt gói TeX Live đầy đủ

      # Bước 1: Biên dịch LaTeX sang PDF bằng pdflatex
      # Bây giờ pdflatex đã có sẵn từ texlive-full
      - name: Compile LaTeX to PDF
        # Không cần dùng xu-cheng/latex-action@v2 nữa, vì pdflatex đã có sẵn
        # và make4ht không thể chạy trong môi trường riêng của latex-action
        run: |
          # pdflatex -output-directory=output/pdf main.tex
          # Hoặc dùng latexmk cho tiện lợi hơn (latexmk cũng có trong texlive-full)
          latexmk -pdf -outdir=output/pdf main.tex

      # Bước 2: Chuyển đổi LaTeX sang HTML bằng make4ht
      # make4ht bây giờ chắc chắn sẽ có sẵn trong PATH.
      - name: Convert LaTeX to HTML with make4ht
        run: |
          make4ht -d output/html main.tex "html" # Chạy make4ht để tạo HTML trong output/html
          mv output/html/main.html output/html/index.html # Đổi tên thành index.html để làm trang mặc định
          ls -l output/html/ # Liệt kê nội dung thư mục để kiểm tra (debug)
          if [ ! -f output/html/index.html ]; then
            echo "Lỗi: index.html không được tạo ra hoặc đổi tên thành công bởi make4ht."
            exit 1 # Thoát job nếu file không tồn tại
          fi

      # Bước 3: Upload file PDF đã biên dịch làm Artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf # Tên của artifact (sẽ hiển thị trên GitHub Actions)
          path: output/pdf/main.pdf # Đường dẫn đến file PDF đã biên dịch

      # Bước 4: Upload các file HTML làm Artifact cho GitHub Pages
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/html # Đường dẫn đến thư mục chứa tất cả các file HTML và tài nguyên liên quan

  # Job phụ trợ để cấu hình GitHub Pages (đảm bảo cấu hình một lần)
  setup-pages:
    runs-on: ubuntu-latest
    needs: build-documents # Job này cần job build-documents chạy xong để có artifacts

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4 # Action để cấu hình Pages, thường chạy một lần

  # Job cuối cùng: Triển khai các file đã tạo lên GitHub Pages
  deploy-pages:
    environment:
      name: github-pages # Chỉ định môi trường triển khai là 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }} # Lấy URL của trang đã triển khai
    runs-on: ubuntu-latest
    needs: [build-documents, setup-pages] # Job này phụ thuộc vào cả hai job trước đó

    steps:
      - name: Deploy to GitHub Pages # Bước: Triển khai nội dung lên GitHub Pages
        id: deployment # Đặt ID cho bước này để có thể tham chiếu URL sau
        uses: actions/deploy-pages@v4 # Action để triển khai lên GitHub Pages